// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Collar is the predicate function for collar builders.
type Collar func(*sql.Selector)

// Media is the predicate function for media builders.
type Media func(*sql.Selector)

// Owner is the predicate function for owner builders.
type Owner func(*sql.Selector)

// Pet is the predicate function for pet builders.
type Pet func(*sql.Selector)
