// Code generated by entc, DO NOT EDIT.

package http

import (
	"net/http"
	"strconv"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"github.com/mailru/easyjson"
	"github.com/masseelch/elk/internal/pets/ent"
	"github.com/masseelch/elk/internal/pets/ent/badge"
	"github.com/masseelch/elk/internal/pets/ent/pet"
	"github.com/masseelch/elk/internal/pets/ent/playgroup"
	"github.com/masseelch/elk/internal/pets/ent/toy"
	"go.uber.org/zap"
)

// Read fetches the ent.Badge identified by a given url-parameter from the
// database and renders it to the client.
func (h *BadgeHandler) Read(w http.ResponseWriter, r *http.Request) {
	l := h.log.With(zap.String("method", "Read"))
	// ID is URL parameter.
	id64, err := strconv.ParseInt(chi.URLParam(r, "id"), 10, 0)
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", chi.URLParam(r, "id")), zap.Error(err))
		BadRequest(w, "id must be an integer greater zero")
		return
	}
	id := uint32(id64)
	// Create the query to fetch the Badge
	q := h.client.Badge.Query().Where(badge.ID(id))
	e, err := q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Uint32("id", id))
			NotFound(w, msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Uint32("id", id))
			BadRequest(w, msg)
		default:
			l.Error("could not read badge", zap.Error(err), zap.Uint32("id", id))
			InternalServerError(w, nil)
		}
		return
	}
	l.Info("badge rendered", zap.Uint32("id", id))
	easyjson.MarshalToHTTPResponseWriter(NewBadgeView(e), w)
}

// Read fetches the ent.Pet identified by a given url-parameter from the
// database and renders it to the client.
func (h *PetHandler) Read(w http.ResponseWriter, r *http.Request) {
	l := h.log.With(zap.String("method", "Read"))
	// ID is URL parameter.
	id, err := strconv.Atoi(chi.URLParam(r, "id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", chi.URLParam(r, "id")), zap.Error(err))
		BadRequest(w, "id must be an integer")
		return
	}
	// Create the query to fetch the Pet
	q := h.client.Pet.Query().Where(pet.ID(id))
	// Eager load edges that are required on read operation.
	q.WithBadge().WithProtege(func(q *ent.PetQuery) {
		q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
			q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithToys().WithParent(func(q *ent.PetQuery) {
			q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
			q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			})
		})
	}).WithSpouse(func(q *ent.PetQuery) {
		q.WithBadge().WithProtege(func(q *ent.PetQuery) {
			q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithToys().WithParent(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			})
		})
	}).WithToys().WithParent(func(q *ent.PetQuery) {
		q.WithBadge().WithProtege(func(q *ent.PetQuery) {
			q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithSpouse(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			})
		}).WithToys().WithParent(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				})
			}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				})
			})
		}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				}).WithPlayGroups()
			})
		})
	}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
		q.WithBadge().WithProtege(func(q *ent.PetQuery) {
			q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			})
		}).WithSpouse(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			})
		}).WithToys().WithParent(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					})
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				})
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						})
					}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					})
				}).WithToys().WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				})
			}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				}).WithPlayGroups()
			})
		}).WithPlayGroups().WithFriends(func(q *ent.PetQuery) {
			q.WithBadge().WithProtege(func(q *ent.PetQuery) {
				q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			}).WithSpouse(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithPlayGroups()
			}).WithToys().WithParent(func(q *ent.PetQuery) {
				q.WithBadge().WithProtege(func(q *ent.PetQuery) {
					q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithSpouse(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithToys().WithParent(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithPlayGroups()
					}).WithToys().WithParent(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithPlayGroups()
				}).WithToys().WithParent(func(q *ent.PetQuery) {
					q.WithBadge().WithProtege(func(q *ent.PetQuery) {
						q.WithBadge().WithSpouse(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithSpouse(func(q *ent.PetQuery) {
						q.WithBadge().WithProtege(func(q *ent.PetQuery) {
							q.WithBadge().WithToys().WithPlayGroups()
						}).WithToys().WithPlayGroups()
					}).WithToys().WithPlayGroups()
				}).WithPlayGroups()
			}).WithPlayGroups()
		})
	})
	e, err := q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			NotFound(w, msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			BadRequest(w, msg)
		default:
			l.Error("could not read pet", zap.Error(err), zap.Int("id", id))
			InternalServerError(w, nil)
		}
		return
	}
	l.Info("pet rendered", zap.Int("id", id))
	easyjson.MarshalToHTTPResponseWriter(NewPetReadView(e), w)
}

// Read fetches the ent.PlayGroup identified by a given url-parameter from the
// database and renders it to the client.
func (h *PlayGroupHandler) Read(w http.ResponseWriter, r *http.Request) {
	l := h.log.With(zap.String("method", "Read"))
	// ID is URL parameter.
	id, err := strconv.Atoi(chi.URLParam(r, "id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", chi.URLParam(r, "id")), zap.Error(err))
		BadRequest(w, "id must be an integer")
		return
	}
	// Create the query to fetch the PlayGroup
	q := h.client.PlayGroup.Query().Where(playgroup.ID(id))
	e, err := q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.Int("id", id))
			NotFound(w, msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.Int("id", id))
			BadRequest(w, msg)
		default:
			l.Error("could not read play-group", zap.Error(err), zap.Int("id", id))
			InternalServerError(w, nil)
		}
		return
	}
	l.Info("play-group rendered", zap.Int("id", id))
	easyjson.MarshalToHTTPResponseWriter(NewPlayGroupView(e), w)
}

// Read fetches the ent.Toy identified by a given url-parameter from the
// database and renders it to the client.
func (h *ToyHandler) Read(w http.ResponseWriter, r *http.Request) {
	l := h.log.With(zap.String("method", "Read"))
	// ID is URL parameter.
	id, err := uuid.Parse(chi.URLParam(r, "id"))
	if err != nil {
		l.Error("error getting id from url parameter", zap.String("id", chi.URLParam(r, "id")), zap.Error(err))
		BadRequest(w, "id must be a valid UUID")
		return
	}
	// Create the query to fetch the Toy
	q := h.client.Toy.Query().Where(toy.ID(uuid.UUID(id)))
	e, err := q.Only(r.Context())
	if err != nil {
		switch {
		case ent.IsNotFound(err):
			msg := stripEntError(err)
			l.Info(msg, zap.Error(err), zap.String("id", id.String()))
			NotFound(w, msg)
		case ent.IsNotSingular(err):
			msg := stripEntError(err)
			l.Error(msg, zap.Error(err), zap.String("id", id.String()))
			BadRequest(w, msg)
		default:
			l.Error("could not read toy", zap.Error(err), zap.String("id", id.String()))
			InternalServerError(w, nil)
		}
		return
	}
	l.Info("toy rendered", zap.String("id", id.String()))
	easyjson.MarshalToHTTPResponseWriter(NewToyView(e), w)
}
