// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Compartment is the predicate function for compartment builders.
type Compartment func(*sql.Selector)

// Content is the predicate function for content builders.
type Content func(*sql.Selector)

// Fridge is the predicate function for fridge builders.
type Fridge func(*sql.Selector)
