// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/masseelch/elk/internal/integration/pets/ent/playgroup"
	"github.com/masseelch/elk/internal/integration/pets/ent/predicate"
)

// PlayGroupDelete is the builder for deleting a PlayGroup entity.
type PlayGroupDelete struct {
	config
	hooks    []Hook
	mutation *PlayGroupMutation
}

// Where appends a list predicates to the PlayGroupDelete builder.
func (pgd *PlayGroupDelete) Where(ps ...predicate.PlayGroup) *PlayGroupDelete {
	pgd.mutation.Where(ps...)
	return pgd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pgd *PlayGroupDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pgd.hooks) == 0 {
		affected, err = pgd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PlayGroupMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pgd.mutation = mutation
			affected, err = pgd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pgd.hooks) - 1; i >= 0; i-- {
			if pgd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pgd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pgd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pgd *PlayGroupDelete) ExecX(ctx context.Context) int {
	n, err := pgd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pgd *PlayGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: playgroup.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: playgroup.FieldID,
			},
		},
	}
	if ps := pgd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, pgd.driver, _spec)
}

// PlayGroupDeleteOne is the builder for deleting a single PlayGroup entity.
type PlayGroupDeleteOne struct {
	pgd *PlayGroupDelete
}

// Exec executes the deletion query.
func (pgdo *PlayGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := pgdo.pgd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{playgroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pgdo *PlayGroupDeleteOne) ExecX(ctx context.Context) {
	pgdo.pgd.ExecX(ctx)
}
