// Code generated by entc, DO NOT EDIT.

package http

import (
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/masseelch/elk/internal/simple/ent"
	"go.uber.org/zap"
)

// NewHandler returns a ready to use handler with all generated endpoints mounted.
func NewHandler(c *ent.Client, l *zap.Logger) chi.Router {
	r := chi.NewRouter()
	categoryHandler := NewCategoryHandler(c, l)
	r.Route("/categories", func(r chi.Router) {
		r.Post("/", categoryHandler.Create)
		r.Get("/{id}", categoryHandler.Read)
		r.Patch("/{id}", categoryHandler.Update)
		r.Delete("/{id}", categoryHandler.Delete)
		r.Get("/", categoryHandler.List)
		r.Get("/{id}/pets", categoryHandler.Pets)
	})
	ownerHandler := NewOwnerHandler(c, l)
	r.Route("/owners", func(r chi.Router) {
		r.Post("/", ownerHandler.Create)
		r.Get("/{id}", ownerHandler.Read)
		r.Patch("/{id}", ownerHandler.Update)
		r.Delete("/{id}", ownerHandler.Delete)
		r.Get("/", ownerHandler.List)
		r.Get("/{id}/pets", ownerHandler.Pets)
	})
	petHandler := NewPetHandler(c, l)
	r.Route("/pets", func(r chi.Router) {
		r.Post("/", petHandler.Create)
		r.Get("/{id}", petHandler.Read)
		r.Patch("/{id}", petHandler.Update)
		r.Delete("/{id}", petHandler.Delete)
		r.Get("/", petHandler.List)
		r.Get("/{id}/categories", petHandler.Categories)
		r.Get("/{id}/owner", petHandler.Owner)
		r.Get("/{id}/friends", petHandler.Friends)
	})
	return r
}

// CategoryHandler handles http crud operations on ent.Category.
type CategoryHandler struct {
	client *ent.Client
	log    *zap.Logger
}

func NewCategoryHandler(c *ent.Client, l *zap.Logger) *CategoryHandler {
	return &CategoryHandler{
		client: c,
		log:    l.With(zap.String("handler", "CategoryHandler")),
	}
}

// OwnerHandler handles http crud operations on ent.Owner.
type OwnerHandler struct {
	client *ent.Client
	log    *zap.Logger
}

func NewOwnerHandler(c *ent.Client, l *zap.Logger) *OwnerHandler {
	return &OwnerHandler{
		client: c,
		log:    l.With(zap.String("handler", "OwnerHandler")),
	}
}

// PetHandler handles http crud operations on ent.Pet.
type PetHandler struct {
	client *ent.Client
	log    *zap.Logger
}

func NewPetHandler(c *ent.Client, l *zap.Logger) *PetHandler {
	return &PetHandler{
		client: c,
		log:    l.With(zap.String("handler", "PetHandler")),
	}
}

func stripEntError(err error) string {
	return strings.TrimPrefix(err.Error(), "ent: ")
}

func zapFields(errs map[string]string) []zap.Field {
	if errs == nil || len(errs) == 0 {
		return nil
	}
	r := make([]zap.Field, 0)
	for k, v := range errs {
		r = append(r, zap.String(k, v))
	}
	return r
}
