// Code generated by entc, DO NOT EDIT.

package http

import "github.com/masseelch/elk/internal/integration/pets/ent"

// Response of a ent.Category create request.
type CategoryCreateResponse struct {
	ID   int    `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}

func NewCategoryCreateResponse(e *ent.Category) *CategoryCreateResponse {
	return &CategoryCreateResponse{
		ID:   e.ID,
		Name: e.Name,
	}
}

// Response of a ent.Category read request.
type CategoryReadResponse struct {
	ID   int    `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}

func NewCategoryReadResponse(e *ent.Category) *CategoryReadResponse {
	return &CategoryReadResponse{
		ID:   e.ID,
		Name: e.Name,
	}
}

// Response of a ent.Category update request.
type CategoryUpdateResponse struct {
	ID   int    `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}

func NewCategoryUpdateResponse(e *ent.Category) *CategoryUpdateResponse {
	return &CategoryUpdateResponse{
		ID:   e.ID,
		Name: e.Name,
	}
}

// Response of a ent.Category list request.
type CategoryListResponse []struct {
	ID   int    `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}

func NewCategoryListResponse(e []*ent.Category) CategoryListResponse {
	r := make(CategoryListResponse, len(e))
	for i := range e {
		r[i] = struct {
			ID   int    `json:"id,omitempty"`
			Name string `json:"name,omitempty"`
		}{
			ID:   e[i].ID,
			Name: e[i].Name,
		}
	}
	return r
}

// Response of a ent.Owner create request.
type OwnerCreateResponse struct {
	ID   int    `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Age  int    `json:"age,omitempty"`
}

func NewOwnerCreateResponse(e *ent.Owner) *OwnerCreateResponse {
	return &OwnerCreateResponse{
		ID:   e.ID,
		Name: e.Name,
		Age:  e.Age,
	}
}

// Response of a ent.Owner read request.
type OwnerReadResponse struct {
	ID   int    `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Age  int    `json:"age,omitempty"`
}

func NewOwnerReadResponse(e *ent.Owner) *OwnerReadResponse {
	return &OwnerReadResponse{
		ID:   e.ID,
		Name: e.Name,
		Age:  e.Age,
	}
}

// Response of a ent.Owner update request.
type OwnerUpdateResponse struct {
	ID   int    `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Age  int    `json:"age,omitempty"`
}

func NewOwnerUpdateResponse(e *ent.Owner) *OwnerUpdateResponse {
	return &OwnerUpdateResponse{
		ID:   e.ID,
		Name: e.Name,
		Age:  e.Age,
	}
}

// Response of a ent.Owner list request.
type OwnerListResponse []struct {
	ID   int    `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Age  int    `json:"age,omitempty"`
}

func NewOwnerListResponse(e []*ent.Owner) OwnerListResponse {
	r := make(OwnerListResponse, len(e))
	for i := range e {
		r[i] = struct {
			ID   int    `json:"id,omitempty"`
			Name string `json:"name,omitempty"`
			Age  int    `json:"age,omitempty"`
		}{
			ID:   e[i].ID,
			Name: e[i].Name,
			Age:  e[i].Age,
		}
	}
	return r
}

// Response of a ent.Pet create request.
type PetCreateResponse struct {
	ID   int    `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Age  int    `json:"age,omitempty"`
}

func NewPetCreateResponse(e *ent.Pet) *PetCreateResponse {
	return &PetCreateResponse{
		ID:   e.ID,
		Name: e.Name,
		Age:  e.Age,
	}
}

// Response of a ent.Pet read request.
type PetReadResponse struct {
	ID    int    `json:"id,omitempty"`
	Name  string `json:"name,omitempty"`
	Age   int    `json:"age,omitempty"`
	Owner struct {
		ID   int    `json:"id,omitempty"`
		Name string `json:"name,omitempty"`
		Age  int    `json:"age,omitempty"`
	} `json:"owner,omitempty"`
	Friends []struct {
		ID    int    `json:"id,omitempty"`
		Name  string `json:"name,omitempty"`
		Age   int    `json:"age,omitempty"`
		Owner struct {
			ID   int    `json:"id,omitempty"`
			Name string `json:"name,omitempty"`
			Age  int    `json:"age,omitempty"`
		} `json:"owner,omitempty"`
		Friends []struct {
			ID    int    `json:"id,omitempty"`
			Name  string `json:"name,omitempty"`
			Age   int    `json:"age,omitempty"`
			Owner struct {
				ID   int    `json:"id,omitempty"`
				Name string `json:"name,omitempty"`
				Age  int    `json:"age,omitempty"`
			} `json:"owner,omitempty"`
			Friends []struct {
				ID    int    `json:"id,omitempty"`
				Name  string `json:"name,omitempty"`
				Age   int    `json:"age,omitempty"`
				Owner struct {
					ID   int    `json:"id,omitempty"`
					Name string `json:"name,omitempty"`
					Age  int    `json:"age,omitempty"`
				} `json:"owner,omitempty"`
			} `json:"friends,omitempty"`
		} `json:"friends,omitempty"`
	} `json:"friends,omitempty"`
}

func NewPetReadResponse(e *ent.Pet) *PetReadResponse {
	owner1 := struct {
		ID   int    `json:"id,omitempty"`
		Name string `json:"name,omitempty"`
		Age  int    `json:"age,omitempty"`
	}{
		ID:   e.Edges.Owner.ID,
		Name: e.Edges.Owner.Name,
		Age:  e.Edges.Owner.Age,
	}
	friends1 := make([]struct {
		ID    int    `json:"id,omitempty"`
		Name  string `json:"name,omitempty"`
		Age   int    `json:"age,omitempty"`
		Owner struct {
			ID   int    `json:"id,omitempty"`
			Name string `json:"name,omitempty"`
			Age  int    `json:"age,omitempty"`
		} `json:"owner,omitempty"`
		Friends []struct {
			ID    int    `json:"id,omitempty"`
			Name  string `json:"name,omitempty"`
			Age   int    `json:"age,omitempty"`
			Owner struct {
				ID   int    `json:"id,omitempty"`
				Name string `json:"name,omitempty"`
				Age  int    `json:"age,omitempty"`
			} `json:"owner,omitempty"`
			Friends []struct {
				ID    int    `json:"id,omitempty"`
				Name  string `json:"name,omitempty"`
				Age   int    `json:"age,omitempty"`
				Owner struct {
					ID   int    `json:"id,omitempty"`
					Name string `json:"name,omitempty"`
					Age  int    `json:"age,omitempty"`
				} `json:"owner,omitempty"`
			} `json:"friends,omitempty"`
		} `json:"friends,omitempty"`
	}, len(e.Edges.Friends))
	for i1 := range e.Edges.Friends {
		owner2 := struct {
			ID   int    `json:"id,omitempty"`
			Name string `json:"name,omitempty"`
			Age  int    `json:"age,omitempty"`
		}{
			ID:   e.Edges.Friends[i1].Edges.Owner.ID,
			Name: e.Edges.Friends[i1].Edges.Owner.Name,
			Age:  e.Edges.Friends[i1].Edges.Owner.Age,
		}
		friends2 := make([]struct {
			ID    int    `json:"id,omitempty"`
			Name  string `json:"name,omitempty"`
			Age   int    `json:"age,omitempty"`
			Owner struct {
				ID   int    `json:"id,omitempty"`
				Name string `json:"name,omitempty"`
				Age  int    `json:"age,omitempty"`
			} `json:"owner,omitempty"`
			Friends []struct {
				ID    int    `json:"id,omitempty"`
				Name  string `json:"name,omitempty"`
				Age   int    `json:"age,omitempty"`
				Owner struct {
					ID   int    `json:"id,omitempty"`
					Name string `json:"name,omitempty"`
					Age  int    `json:"age,omitempty"`
				} `json:"owner,omitempty"`
			} `json:"friends,omitempty"`
		}, len(e.Edges.Friends[i1].Edges.Friends))
		for i2 := range e.Edges.Friends[i1].Edges.Friends {
			owner3 := struct {
				ID   int    `json:"id,omitempty"`
				Name string `json:"name,omitempty"`
				Age  int    `json:"age,omitempty"`
			}{
				ID:   e.Edges.Friends[i1].Edges.Friends[i2].Edges.Owner.ID,
				Name: e.Edges.Friends[i1].Edges.Friends[i2].Edges.Owner.Name,
				Age:  e.Edges.Friends[i1].Edges.Friends[i2].Edges.Owner.Age,
			}
			friends3 := make([]struct {
				ID    int    `json:"id,omitempty"`
				Name  string `json:"name,omitempty"`
				Age   int    `json:"age,omitempty"`
				Owner struct {
					ID   int    `json:"id,omitempty"`
					Name string `json:"name,omitempty"`
					Age  int    `json:"age,omitempty"`
				} `json:"owner,omitempty"`
			}, len(e.Edges.Friends[i1].Edges.Friends[i2].Edges.Friends))
			for i3 := range e.Edges.Friends[i1].Edges.Friends[i2].Edges.Friends {
				owner4 := struct {
					ID   int    `json:"id,omitempty"`
					Name string `json:"name,omitempty"`
					Age  int    `json:"age,omitempty"`
				}{
					ID:   e.Edges.Friends[i1].Edges.Friends[i2].Edges.Friends[i3].Edges.Owner.ID,
					Name: e.Edges.Friends[i1].Edges.Friends[i2].Edges.Friends[i3].Edges.Owner.Name,
					Age:  e.Edges.Friends[i1].Edges.Friends[i2].Edges.Friends[i3].Edges.Owner.Age,
				}
				friends3[i3] = struct {
					ID    int    `json:"id,omitempty"`
					Name  string `json:"name,omitempty"`
					Age   int    `json:"age,omitempty"`
					Owner struct {
						ID   int    `json:"id,omitempty"`
						Name string `json:"name,omitempty"`
						Age  int    `json:"age,omitempty"`
					} `json:"owner,omitempty"`
				}{
					ID:    e.Edges.Friends[i1].Edges.Friends[i2].Edges.Friends[i3].ID,
					Name:  e.Edges.Friends[i1].Edges.Friends[i2].Edges.Friends[i3].Name,
					Age:   e.Edges.Friends[i1].Edges.Friends[i2].Edges.Friends[i3].Age,
					Owner: owner4,
				}
			}
			friends2[i2] = struct {
				ID    int    `json:"id,omitempty"`
				Name  string `json:"name,omitempty"`
				Age   int    `json:"age,omitempty"`
				Owner struct {
					ID   int    `json:"id,omitempty"`
					Name string `json:"name,omitempty"`
					Age  int    `json:"age,omitempty"`
				} `json:"owner,omitempty"`
				Friends []struct {
					ID    int    `json:"id,omitempty"`
					Name  string `json:"name,omitempty"`
					Age   int    `json:"age,omitempty"`
					Owner struct {
						ID   int    `json:"id,omitempty"`
						Name string `json:"name,omitempty"`
						Age  int    `json:"age,omitempty"`
					} `json:"owner,omitempty"`
				} `json:"friends,omitempty"`
			}{
				ID:      e.Edges.Friends[i1].Edges.Friends[i2].ID,
				Name:    e.Edges.Friends[i1].Edges.Friends[i2].Name,
				Age:     e.Edges.Friends[i1].Edges.Friends[i2].Age,
				Owner:   owner3,
				Friends: friends3,
			}
		}
		friends1[i1] = struct {
			ID    int    `json:"id,omitempty"`
			Name  string `json:"name,omitempty"`
			Age   int    `json:"age,omitempty"`
			Owner struct {
				ID   int    `json:"id,omitempty"`
				Name string `json:"name,omitempty"`
				Age  int    `json:"age,omitempty"`
			} `json:"owner,omitempty"`
			Friends []struct {
				ID    int    `json:"id,omitempty"`
				Name  string `json:"name,omitempty"`
				Age   int    `json:"age,omitempty"`
				Owner struct {
					ID   int    `json:"id,omitempty"`
					Name string `json:"name,omitempty"`
					Age  int    `json:"age,omitempty"`
				} `json:"owner,omitempty"`
				Friends []struct {
					ID    int    `json:"id,omitempty"`
					Name  string `json:"name,omitempty"`
					Age   int    `json:"age,omitempty"`
					Owner struct {
						ID   int    `json:"id,omitempty"`
						Name string `json:"name,omitempty"`
						Age  int    `json:"age,omitempty"`
					} `json:"owner,omitempty"`
				} `json:"friends,omitempty"`
			} `json:"friends,omitempty"`
		}{
			ID:      e.Edges.Friends[i1].ID,
			Name:    e.Edges.Friends[i1].Name,
			Age:     e.Edges.Friends[i1].Age,
			Owner:   owner2,
			Friends: friends2,
		}
	}
	return &PetReadResponse{
		ID:      e.ID,
		Name:    e.Name,
		Age:     e.Age,
		Owner:   owner1,
		Friends: friends1,
	}
}

// Response of a ent.Pet update request.
type PetUpdateResponse struct {
	ID   int    `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Age  int    `json:"age,omitempty"`
}

func NewPetUpdateResponse(e *ent.Pet) *PetUpdateResponse {
	return &PetUpdateResponse{
		ID:   e.ID,
		Name: e.Name,
		Age:  e.Age,
	}
}

// Response of a ent.Pet list request.
type PetListResponse []struct {
	ID      int    `json:"id,omitempty"`
	Name    string `json:"name,omitempty"`
	Age     int    `json:"age,omitempty"`
	Friends []struct {
		ID      int    `json:"id,omitempty"`
		Name    string `json:"name,omitempty"`
		Age     int    `json:"age,omitempty"`
		Friends []struct {
			ID      int    `json:"id,omitempty"`
			Name    string `json:"name,omitempty"`
			Age     int    `json:"age,omitempty"`
			Friends []struct {
				ID   int    `json:"id,omitempty"`
				Name string `json:"name,omitempty"`
				Age  int    `json:"age,omitempty"`
			} `json:"friends,omitempty"`
		} `json:"friends,omitempty"`
	} `json:"friends,omitempty"`
}

func NewPetListResponse(e []*ent.Pet) PetListResponse {
	r := make(PetListResponse, len(e))
	for i := range e {
		friends1 := make([]struct {
			ID      int    `json:"id,omitempty"`
			Name    string `json:"name,omitempty"`
			Age     int    `json:"age,omitempty"`
			Friends []struct {
				ID      int    `json:"id,omitempty"`
				Name    string `json:"name,omitempty"`
				Age     int    `json:"age,omitempty"`
				Friends []struct {
					ID   int    `json:"id,omitempty"`
					Name string `json:"name,omitempty"`
					Age  int    `json:"age,omitempty"`
				} `json:"friends,omitempty"`
			} `json:"friends,omitempty"`
		}, len(e[i].Edges.Friends))
		for i1 := range e[i].Edges.Friends {
			friends2 := make([]struct {
				ID      int    `json:"id,omitempty"`
				Name    string `json:"name,omitempty"`
				Age     int    `json:"age,omitempty"`
				Friends []struct {
					ID   int    `json:"id,omitempty"`
					Name string `json:"name,omitempty"`
					Age  int    `json:"age,omitempty"`
				} `json:"friends,omitempty"`
			}, len(e[i].Edges.Friends[i1].Edges.Friends))
			for i2 := range e[i].Edges.Friends[i1].Edges.Friends {
				friends3 := make([]struct {
					ID   int    `json:"id,omitempty"`
					Name string `json:"name,omitempty"`
					Age  int    `json:"age,omitempty"`
				}, len(e[i].Edges.Friends[i1].Edges.Friends[i2].Edges.Friends))
				for i3 := range e[i].Edges.Friends[i1].Edges.Friends[i2].Edges.Friends {
					friends3[i3] = struct {
						ID   int    `json:"id,omitempty"`
						Name string `json:"name,omitempty"`
						Age  int    `json:"age,omitempty"`
					}{
						ID:   e[i].Edges.Friends[i1].Edges.Friends[i2].Edges.Friends[i3].ID,
						Name: e[i].Edges.Friends[i1].Edges.Friends[i2].Edges.Friends[i3].Name,
						Age:  e[i].Edges.Friends[i1].Edges.Friends[i2].Edges.Friends[i3].Age,
					}
				}
				friends2[i2] = struct {
					ID      int    `json:"id,omitempty"`
					Name    string `json:"name,omitempty"`
					Age     int    `json:"age,omitempty"`
					Friends []struct {
						ID   int    `json:"id,omitempty"`
						Name string `json:"name,omitempty"`
						Age  int    `json:"age,omitempty"`
					} `json:"friends,omitempty"`
				}{
					ID:      e[i].Edges.Friends[i1].Edges.Friends[i2].ID,
					Name:    e[i].Edges.Friends[i1].Edges.Friends[i2].Name,
					Age:     e[i].Edges.Friends[i1].Edges.Friends[i2].Age,
					Friends: friends3,
				}
			}
			friends1[i1] = struct {
				ID      int    `json:"id,omitempty"`
				Name    string `json:"name,omitempty"`
				Age     int    `json:"age,omitempty"`
				Friends []struct {
					ID      int    `json:"id,omitempty"`
					Name    string `json:"name,omitempty"`
					Age     int    `json:"age,omitempty"`
					Friends []struct {
						ID   int    `json:"id,omitempty"`
						Name string `json:"name,omitempty"`
						Age  int    `json:"age,omitempty"`
					} `json:"friends,omitempty"`
				} `json:"friends,omitempty"`
			}{
				ID:      e[i].Edges.Friends[i1].ID,
				Name:    e[i].Edges.Friends[i1].Name,
				Age:     e[i].Edges.Friends[i1].Age,
				Friends: friends2,
			}
		}
		r[i] = struct {
			ID      int    `json:"id,omitempty"`
			Name    string `json:"name,omitempty"`
			Age     int    `json:"age,omitempty"`
			Friends []struct {
				ID      int    `json:"id,omitempty"`
				Name    string `json:"name,omitempty"`
				Age     int    `json:"age,omitempty"`
				Friends []struct {
					ID      int    `json:"id,omitempty"`
					Name    string `json:"name,omitempty"`
					Age     int    `json:"age,omitempty"`
					Friends []struct {
						ID   int    `json:"id,omitempty"`
						Name string `json:"name,omitempty"`
						Age  int    `json:"age,omitempty"`
					} `json:"friends,omitempty"`
				} `json:"friends,omitempty"`
			} `json:"friends,omitempty"`
		}{
			ID:      e[i].ID,
			Name:    e[i].Name,
			Age:     e[i].Age,
			Friends: friends1,
		}
	}
	return r
}
